# Generated by Django 5.1.7 on 2025-03-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
